# Generated by Django 4.0.4 on 2022-04-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feedback',
            new_name='contact',
        ),
    ]
